# Notion ↔ Obsidian Sync Configuration

# Notion Configuration
notion:
  # Your Notion integration token (get from https://www.notion.so/my-integrations)
  token: "secret_your_notion_token_here"
  
  # Database IDs to sync (get from database URLs)
  database_ids:
    - "your_database_id_1"
    - "your_database_id_2"
  
  # Rate limiting (requests per second)
  rate_limit: 3

# Obsidian Configuration
obsidian:
  # Path to your Obsidian vault
  vault_path: "/path/to/your/obsidian/vault"
  
  # Folder within vault for synced content
  sync_folder: "Notion Sync"
  
  # File naming convention
  filename_template: "{title}.md"

# Sync Settings
sync:
  # Sync direction: "bidirectional", "notion_to_obsidian", "obsidian_to_notion"
  direction: "bidirectional"
  
  # Sync interval for continuous sync (seconds)
  interval: 30
  
  # Backup files before overwriting
  create_backups: true
  
  # Maximum backup files to keep
  max_backups: 5

# Conversion Settings
conversion:
  # Convert wikilinks to Notion page mentions
  convert_wikilinks: true
  
  # Convert Notion mentions to wikilinks
  convert_mentions: true
  
  # Preserve frontmatter in Obsidian files
  preserve_frontmatter: true
  
  # Include Notion metadata in frontmatter
  include_notion_metadata: true
  
  # Image handling: "link", "download", "embed"
  image_handling: "link"

# Conflict Resolution
conflict_resolution:
  # Strategy: "manual", "notion_wins", "obsidian_wins", "newest_wins"
  strategy: "newest_wins"
  
  # Create conflict files for manual resolution
  create_conflict_files: true

# Logging
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# Advanced Settings
advanced:
  # Enable experimental features
  experimental_features: false
  
  # Custom property mappings
  property_mappings:
    # Map Obsidian frontmatter keys to Notion properties
    "tags": "Tags"
    "status": "Status"
    "priority": "Priority"
    "due_date": "Due Date"
  
  # Exclude patterns (files/folders to ignore)
  exclude_patterns:
    - "*.tmp"
    - ".obsidian/*"
    - "Templates/*"
  
  # Include only specific file patterns
  include_patterns:
    - "*.md"

